### PR TITLE
Godot 3.0 migration

### PR DESCRIPTION
**Pull request by StraToN**
I started migrating this plugin to 3.0.
All features & demos work, except:
- ~~Trailing particles. Particle2D node has changed a bit and I didn't succeed in making it work the same as previously. I'll try to continue the work and get it working, but if someone knows this better I'll gladly accept to help or hints.~~ Fixed

I had to fiddle with `set_process()` and `set_process_input()` initialization in `swipe_detector.gd::set_swipe_process()` because Godot 3.0 sets process modes by default.
I also had to modify the angle calculation for it to stay correct in https://github.com/arypbatista/godot-swipe-detector/pull/18/files#diff-fab58008ae53e71bc82d625e2529e4cdR106

### CODE REVIEW

**Comment by arypbatista** [comment]
Hi! Have you tested all demos are running correctly? That's our test suite haha

I will check it out later and merge

Also, I should check if asset library allows to set different version of the plugin for each Godot version (2.1.4 & 3.0)

**Comment by StraToN** [comment]
Hi !
Yep. I tested all of them. I am just not certain of the result for `swipe_touch_smooth_impulse`. 
But ofc I strongly advise you just clone my repo, import it in Godot 3.0 and test :)

Asset Lib allows you to define multiple versions, you just have to create as many releases on your GH repo as versions you want to provide.

**Comment by arypbatista** [comment]
Roger! I will check later and merge!

**Comment by arypbatista** [comment]
Hi Julian! Good job!

Some questions over here:

1. You replaced relative import path with absolute paths on GDScript. Is there a reason for this? I prefer relative imports since it's easy to perform refactoring if needed plus the user of this code can move the swipe detector around without having to change load/preload statements to adjust to new paths.
2. On [event_swipe_input.gd](https://github.com/arypbatista/godot-swipe-detector/pull/18/files#diff-d1db8db28ae6a19186d6ff261913dd15) you commented the line 29 where event checking was performed. This was added to decide what received events will be processed. What is the reason for removing event checking? This seemed to be causing errors when press keys or trigger any other event, so added it again (adapted to Godot 3.0).
3. Fixed angle calculation to fix demos involving swipe direction.

Merged!

Bests,

Ary

**Comment by StraToN** [comment]
Hi !

1. I actually used absolute paths for early convenience and simply forgot to get back to relative paths. For some reason, previous relative paths didn't work in Godot 3.0. It will be better if you can set them back :)
2. I failed translating this to Godot 3.0 because the `type` attribute doesn't exist anymore. I'll look at your solution, I am very interested.
3. I remarked this error just after you merged. Good thing you fixed it :+1:

**Comment by arypbatista** [comment]
2. I don't think my solution is the best one. Maybe there is a more 3.0-godotter approach to do this.
3. I don't really understand how Godot output angles, neither spend time on it. I would expect 0º to be 0, 90º to be PI/2, 180º to be PI, 270º to be PI + PI/2 and 360º to be PI. But they seem to do something different, like going from -PI to PI, and perceive angles are inverted. Maybe this is the way games handle angles, but I am new on this.

Updated demos.

I will update the asset library now.

**Pull request merged**
